### ISSUE TITLE
Allow language translations to be handled by WP repo

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-external-referral-links#15]
We need to update this plugin so the language files are handled by the WP repo. Similar to: easydigitaldownloads/edd-featured-downloads#9

**Comment by DrewAPicture** [comment]
Note: Ask @DrewAPicture for how to best accomplish this.

**Comment by dbeja** [comment]
PR: #28

**Comment by DrewAPicture** [comment]
Merged #28 against `release/1.1`
