### ISSUE TITLE
Update plugin author name and URL

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-external-referral-links#20]
On our testing site I noticed that the author name was `AffiliateWWP`. Since this is a change that is being placed across all of our plugins, it would be good to update: 

- `Author: AffiliateWWP` to `Author: Sandhills Development, LLC`
- `Author URI: https://affiliatewp.com` to `Author URI: https://sandhillsdev.com`

This was done in [Restrict Content Pro](https://github.com/restrictcontentpro/restrict-content-pro/issues/2361) and [AffiliateWP](https://github.com/AffiliateWP/AffiliateWP/issues/3039).

**Comment by michaelbeil** [comment]
I also updated `Plugin URI:` to `Plugin URI: https://affiliatewp.com` in the [PR](https://github.com/AffiliateWP/affiliatewp-external-referral-links/pull/21/files#diff-e4e42d1dc59feb1e2b74ead53d21fb17R4).

**Comment by amdrew** [comment]
Thanks @michaelbeil, merged.
