### ISSUE TITLE
Use tracking cookie name getters

### ISSUE THREAD

**Issue by dbeja** [AffiliateWP/affiliatewp-external-referral-links#33]
On AffiliateWP 2.7.1 it was implemented tracking cookie name getters (AffiliateWP/AffiliateWP#3937) so that the cookie names are not hardcoded on multiple places and to allow changing the cookie names on some specific cases (for example, on a Pantheon's edge network where the cookies need to be prefixed with `wp_`).

These cookie name getters need to be implemented here on this add-on.

**Comment by dbeja** [comment]
PR: #34

**Comment by DrewAPicture** [comment]
Merged #34 against `release/1.1`
