### ISSUE TITLE
Add nag/msg when user activates on a site where AffiliateWP is installed

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-external-referral-links#9]
Would be great if a warning message showed when a user activates the External Referral Link add-on a site that has the main AffiliateWP core plugin installed.

**Comment by amdrew** [comment]
That's a great idea

**Comment by amdrew** [comment]
Unless we get further requests for this I think we should not pursue this. It's possible a customer may want to intentionally do this, for example if they had AffiliateWP on _another_ site.
